### ISSUE TITLE
[BUG] Auto hatchery is syncing main screen pokemon list and hatchery list

### ISSUE THREAD

**Issue by DMaurin** [Ephenia/Pokeclicker-Scripts#10]
With the Enhanced Auto Hatchery (enhancedautohatchery.js) script, changing sorting on either the main script pokemon list or the hatchery list, it also changes the other. Vanilla game allows us to sort the 2 differently and I don't understand why the script would need to synchronize them.

**Comment by Ephenia** [comment]
This is intentional behavior and how I had designed the Enhanced Auto Hatchery to be (to stay true to Ivan Lay's original script with automation of the Hatchery as well). This is more of my own decision, as personally I find that automatically sorting the Hatchery through the Pokémon List can be very convenient with changing Hatchery sorting on the fly. I don't really find it bothersome or annoying, or anything of the sort, either.

However, I will leave a poll here if anyone else would want to see a setting for this feature that can disable the two lists being synchronous at any given time. If there's enough support for it, then I will be more willing to spend the time to incorporate a setting for it sooner rather than later. Otherwise, it will stay as something I won't really be bothering to implement or at the very least remain a very low priority on my to-do list for now.

<p><a href="https://api.gh-polls.com/poll/01FS2PEZQ3P9HN8J48XVCHAXX4/Yes/vote"><img src="https://api.gh-polls.com/poll/01FS2PEZQ3P9HN8J48XVCHAXX4/Yes" alt=""></a>
<a href="https://api.gh-polls.com/poll/01FS2PEZQ3P9HN8J48XVCHAXX4/No/vote"><img src="https://api.gh-polls.com/poll/01FS2PEZQ3P9HN8J48XVCHAXX4/No" alt=""></a>
<a href="https://api.gh-polls.com/poll/01FS2PEZQ3P9HN8J48XVCHAXX4/Neutral/vote"><img src="https://api.gh-polls.com/poll/01FS2PEZQ3P9HN8J48XVCHAXX4/Neutral" alt=""></a></p>

This will remain labelled `wontfix` for the time being.

**Comment by DMaurin** [comment]
Thank you for the reply.

Personally I use 2 different sorting.
On the hatchery screen, I sort by breeding efficiency and a filter on my last region.
On the main screen, I sort by ascending level so I can see my last hatched pokemon. 

I understand it's a personnal preference and I don't know if it bother a lot of people so I understand it's not a priority :) Nice work anyway !

**Comment by Ephenia** [comment]
Due to the already overwhelming and positive support, I will be implementing this in the next revision of the script!

**Comment by Ephenia** [comment]
This is now implemented as of version 1.5 (commit 939c88b65be46f499e45cc4e1eb9f7637b28f097).

If there are any issues with this newly implemented feature, feel free to create and open a new issue.
