### ISSUE TITLE
Catch speed adjuster script is not working

### ISSUE THREAD

**Issue by poukipouki999** [Ephenia/Pokeclicker-Scripts#118]
Hello and first thanks for your work !

Weither I use the script on firefox or chrome, it returns an error on line 15 :

![error2](https://user-images.githubusercontent.com/106375586/170729151-d855ad21-6194-44f4-a76a-94321a7f4b6a.png)

The 'App' object is not defined. What am I doing wrong ?

**Comment by Ephenia** [comment]
Seeing that is normal, App would always show a warning as not being defined:
![image](https://user-images.githubusercontent.com/26987203/170742126-7285ace3-9d05-4a05-87af-023f2cde5114.png)

Warning =/= Error

App is not defined, because it's not defined within the script itself. App is only defined by the game when the game runs, and this portion of the script gets loaded when App is being used and is actually defined by the game. If App gets used when it is not defined by the game, then that's when line 15 would throw an error.

The script should work just fine otherwise, that is, unless you're getting errors in console that sources line 15.

**Comment by poukipouki999** [comment]
The script is working on firefox, I just didn't see I had to check the box 'delay capture' in the pokeball frame.

Thanks for the time you put in that, it's really appreciated !
