### ISSUE TITLE
[Bug] Autoclicker occasionally not working

### ISSUE THREAD

**Issue by umbralOptimatum** [Ephenia/Pokeclicker-Scripts#120]
I have very little sense so far of what causes this, but during the last day or two occasionally the autoclicker just... does not click. I'm still able to deal damage by clicking manually. Possibly connected to a very recent Pokeclicker update or my having just progressed to Alola? I've only noticed this happening in gyms or dungeons; the one instance I'm sure of being the Ultra Necrozma fight. I'll update with more info if it happens again.

**Comment by Ephenia** [comment]
If you are tabbing out and not leaving the game running in the actual background, then that would likely be the reason due to this happening.

That's something technical I haven't really stated in the README, however I would be aware of it. These scripts just wouldn't be using service workers, so what these scripts can do essentially can be throttled. If you can disable throttling done by the client (browser), then there shouldn't be any issues I believe so.

I haven't messed much around with Alola, but I don't think it would be the issue or related.

**Comment by locobastos** [comment]
Hello!

I had the same issue on my main web browser (MS Edge), I tried on a fresh and unused browser (Firefox) and every scripts work well. No throttle. I thiunk that some addons impact pokéclicker-scripts...

@umbralOptimatum Could you please try with a clean (no addons/extensions) browser?

**Comment by ArrikTTV** [comment]
Auto clicker, Auto Gym and Auto dungeon F/B don't work 
I use Brave & Chrome Browser

**Comment by umbralOptimatum** [comment]
> If you are tabbing out and not leaving the game running in the actual background, then that would likely be the reason due to this happening.

I had noticed the autoclicker not running if the game wasn't the active tab in its window, but this happened while I was actively playing. The script was working properly for most of it but occasionally it just did nothing for a single fight! Very bizarre.

> I haven't messed much around with Alola, but I don't think it would be the issue or related.

Agreed, much more likely I simply noticed because of the longer battles. I only brought it up in case Alola's different gym and boss design is handled differently code-wise.

> @umbralOptimatum Could you please try with a clean (no addons/extensions) browser?

Thank you for the suggestion, but given how intermittent the issue is I don't think I can test that effectively. I use Firefox with a handful of extensions but none of them have updated within the timeframe I started noticing this.

**Comment by Ephenia** [comment]
I was thinking that it could also be due to my method of doing source modification to the game via script with the latest updates, since well, I still consider this something more experimental that I'm playing around with. Also, it could be that the Auto Clicker statistics may be throwing you off, since for example things like catching will stop DPS calculation briefly, which is a new feature. But, that's also intentional design by me.

**Comment by umbralOptimatum** [comment]
It's not the DPS statistics; the few time it's happened has been in long enough battles to tell that the opponent's health isn't going down between pokemon attacks (and that it does take damage from clicking manually).
