### ISSUE TITLE
[Feature request] Auto Quest : corrupted script or bad handling?

### ISSUE THREAD

**Issue by nheero91** [Ephenia/Pokeclicker-Scripts#148]
Hello, I would like to have a little information about this script, recently the quest script went from 7 to 4 (as if it was not activated) I tried to reinstall but nothing happens.
I see selectable quests but impossible to add them manually in the list, once these few quests finish it generates a new list by abandoning all the others (sometimes several thousands of tokens lost...) tamper Monkey is well up to date as well as chrome I do not understand, someone would have already had this worry?
sorry for my english but google does the job ^^

**Comment by Mega-Rayquaza-8121** [comment]
<img width="588" alt="image" src="https://user-images.githubusercontent.com/62550729/172973678-92196087-0de2-42c9-ba4b-9275adccf1aa.png">
if you click this area, it allows you to sort quests and makes it so that it accepts or doesn't accept the specific type of quest. it's an intended feature i believe

**Comment by nheero91** [comment]
I didn't have this problem before, the quests were displayed and then disappeared by themselves, now I have to click on activate to generate a new list / deactivate the auto and then click on the quests I want to have. My friend who has the same script her list updates by itself.
