### ISSUE TITLE
Auto click Boost 1x/100

### ISSUE THREAD

**Issue by Unfo0** [Ephenia/Pokeclicker-Scripts#149]
Bonjour j'aimerai savoir comment il serais possible d'avoir l'auto click boosté en permanence (si possible)
Un coup celui ci est a 400k DPS/CLIK et parfois a 7M.
(Désolé si un post a déjà était fait ou on c'est la première fois que j'interviens ici)

**Comment by Mega-Rayquaza-8121** [comment]
translation (my french is bad so if wrong correct me, google translate is not accurate)
hello i'd like to know how to have permanently boosted auto clicker (if possible)
one click here is around 400k dps and sometimes it reaches 7m 
(sorry if a post has already been done here on this it's the first time i post here)

at the moment, the autoclicker is kind of inconsistent, i also am not sure how it works but you can adjust the number of clicks per second up to 1000 clicks per second, you should probably ignore the req. dps and the enemy per second for the moment because it's often inaccurate, probably it will be fixed but for the moment that's a bit of an issue

au moment, l'auto click est un peu inconsistant, je ne suis pas sûr comment ça marche mais vous pouvez ajuster le nombre de clics par seconde jusqu'à 1000 clics par seconde, vous devriez peut-être ignorer ces nombres ici parce qu'ils sont souvent imprécis, ça sera probablement fixé plus tard mais au moment c'est un petit problème 
sorry for bad french i am still learning

<img width="415" alt="image" src="https://user-images.githubusercontent.com/62550729/173475521-f106db2e-bff7-46a0-977c-1a9dc50b9cf3.png">

**Comment by Unfo0** [comment]
Oui j'ai bien régulé mon autoclicker aux 1k clic/sec.
D'accord je vois donc des journées en ayant 7M de dégâts constant (pas mal pour le farm sa) est donc un "bug" ?
( Votre google translate est bon ne vous inquiétez pas)

**Comment by Mega-Rayquaza-8121** [comment]
je pense que les dégâts constant n'est pas un bug, c'est quand ils changent aux nombres qui sont moins que les nombres actuelles.
je dis ça parce que après un update le plus récent, je ne vois jamais de dégâts constant, ils changent chaque seconde et comme vous voyez le "enemy/s" est parfois zéro qui n'est pas possible. si votre dégâts sont constant je pense qu'il n'y avait pas de problème mais s'ils sont moins que les nombres actuelles c'est l'inconsistence dont je parle.

**Comment by Unfo0** [comment]
Je vois. Mais parfois il y a vraiment une différence de dégâts colossale que je n'arrive pas a garder des que je reset ou ferme ma page.

**Comment by Ephenia** [comment]
Lorsque vous fermez la page et que vous ne laissez pas le jeu s'exécuter en arrière-plan, le clic automatique sera limité.

Donc, si vous sortez du jeu ou réduisez la fenêtre, votre Auto Clicker ne fonctionnera pas avec une efficacité maximale, c'est normal. Les scripts n'utilisent pas et/ou n'utilisent pas les service workers. C'est la raison pour laquelle.

**Comment by Mega-Rayquaza-8121** [comment]
oh that makes a lot of sense because i leave it in background, but i allowed background tab to run at full speed, does that still result in the issue
because last time when it was capped 20 cps it worked fine but after i updated to the slider thing then it became inconsistent
