### ISSUE TITLE
Auto Hatchery stopped working on desktop on version 0.9.5

### ISSUE THREAD

**Issue by quik2903** [Ephenia/Pokeclicker-Scripts#158]
I play on the Windows desktop version. I haven't updated to 0.9.6, but auto hatchery has stopped working. The buttons show up, but no eggs are added to the hatchery. The Auto Fossil and Auto Egg features do work, though. I tried to restart the game, to enable and disable the script (with their respective restarts) and to overwrite the app.asar file, but none of these worked.

**Comment by Dionisos94** [comment]
Which version of the auto hatchery script are you using ?
If you dont want to update, you will need to use a version before the commits on the 26th
https://github.com/Ephenia/Pokeclicker-Scripts/commits/master/enhancedautohatchery.user.js

**Comment by quik2903** [comment]
The script version is 1.6, which seems to correspond with the latest version. Do these scripts update automatically? That would explain it. Is there a way to avoid this update process? Thank you very much!

**Comment by Dionisos94** [comment]
V1.6 contains yesterday changes which were made for pokeclicker v0.9.6 and are unhappily not retroactive.
I do not know how the scripts work for windows and how they are updated so I am not of a great help here :(

**Comment by Ephenia** [comment]
The scripts should update automatically and should also support new scripts, at least this is the design of it and how I made the client edit initially work, but then again ever since catchfilterfantasia got introduced, that has also been causing problems.

It's likely that the custom edit needs to be updated and needs to be looked at, but then again I haven't touched this or have been wanting to maintain this since January.

**Comment by quik2903** [comment]
I think I'll update to 0.9.7, since now the XP nerf isn't that bad, and everything should work ok. Thanks for taking the time of looking into it.
