### ISSUE TITLE
Auto Dungeon is broken after new update 0.9.8

### ISSUE THREAD

**Issue by DataCrusade** [Ephenia/Pokeclicker-Scripts#178]
After the new update, attempting to use auto dungeon will spam starting the dungeon repeatedly eating through dungeon tokens without actually progressing the dungeon

**Comment by DataCrusade** [comment]
Auto gym is also sorta broken? Similar issue where it just keeps restarting over and over

**Comment by DataCrusade** [comment]
Seems like they straight up don't work at all if auto click is off as well

**Comment by alcibar19** [comment]
it definitely is broken. I have to manually do the dungeons to finish my dungeons quests. If you manually entered the dungeon, the screen becomes static when you turn the autodungeon on.

**Comment by klundberg** [comment]
Auto Gym is also apparently broken in a similar manner, rapidly stopping and starting a gym battle instead of only starting it when returning to the regular screen for a location.

**Comment by gdl43300** [comment]
I think the problem comes from the new current location marker, it break the current location check in the auto dungeon and auto gym. I don't understand why there is this check, I just remove it from my script and it seems to work again
```
if (MapHelper.calculateTownCssClass(player.town().name) != "currentLocation") {
  MapHelper.moveToTown(player.town().name)
}
```

**Comment by Ephenia** [comment]
Okay, here's to the 🤡 and the those who just want to talk big and don't understand why that check was there in the first place and act hard or as if it was just put there as soon as the update happened. Meanwhile, this was there the WHOLE time ever since I created the script and there was never any issues until this update with the game now.

For the people who don't really understand code or really the technical side of things at all, let's go reference the documentation for Auto Gym as well as Auto Gym, as these both broke with this update, yes? Okay, here we go:

> • Auto Gym when activated will automatically fight the Gym in the town you are in or the one you visited last (if it has a Gym).

> • Auto Dungeon when activated will automatically fight the current dungeon, the last dungeon you've visited or the dungeon in the one in the last town you were in (if it has one).

Now, that check (the 3 lines of code being referenced), is essentially for making sure that you ARE in the correct location while you are autoing a Gym OR a dungeon. This check disallows you to move across routes while you are autoing, which is otherwise normally impossible. It will also properly move you to where you should be at, even if you activate Auto Gym or Auto Dungeon when you are currently in a route.

You can try deleting those 3 lines of code, and yes, while it will still work, it still is not correct, and it still exposes bugs that are unnatural things that are impossible to perform normally (if an actual human were doing it). If you try moving to routes prior to the update and now after the update (with v2.1 of the script), then you will still be locked right back to the Gym/Dungeon that you're autoing. This would be a lot more relevant for Auto Gym than Auto Dungeon, since it's much harder to navigate the Town Map while you have Auto Dungeon running.

Like sure, if you don't care about this bug and are just happy with a solution that works, then more power to you. It's after all, not a game breaking bug and nothing too serious. But you see here, I do have standards and try to ensure that there is at least decent quality being had at least with how things are functioning. Yeah, not saying anything or everything with my coding in these scripts are stellar (especially these earlier ones I made when I had started this project). They're very far from anything like that, and even I know that.

The new code is those old 3 lines of code, now changed to this:

```
const townName = player.town().name;
if (!MapHelper.isTownCurrentLocation(townName)) {
    MapHelper.moveToTown(townName)
}
```

Does and accomplishes the same exact thing as those other 3 lines of code as before when they worked without issue in the previous versions of the game, and this would be even more simple to understand as well with what I'm explaining.

I really appreciate those who just like waited patiently for a proper fix on my behalf and for me to update things. I appreciate those to that properly and or politely point out that there's an issue and something is broken with the script. Likewise, I also appreciate those that help try to fix these issues or offer to help, maybe even send in and propose a PR, or just like to offer some sort of temporary solution in the meantime while things are properly updated.

However, one thing that I don't appreciate is those who don't really at least try to look at the documentation, or really like try to understand why something works and doing what it does, or even test things themselves, before coming to the all time conclusion and saying "hey, this is useless". Picking at code is absolutely no exception to this, and it's best not to say anything if you don't actually know or even just at least ask as to why it's there.

Also, yes, as you can see I'm quite annoyed, because stuff like this should be so trivial, and I shouldn't even have to deal with negativity.
