### ISSUE TITLE
The scripts won't load properly on the client version.

### ISSUE THREAD

**Issue by Murokyro** [Ephenia/Pokeclicker-Scripts#19]
Hello, i have a problem where the scripts won't properly load whenever i start the client version of the game. I tried restarting it multiples times but each time it's a different script that won't load, for instance i currently have the autoclicker, the autohatchery, the automine, the catchspeedadjuster but the autofarm didn't load.

**Comment by Ephenia** [comment]
Did the client download all the scripts into the correct designated folder? Also, are you messing around with the custom script loading at all? Since, I know that this can be an issue currently when changing/modifying scripts and reloading the client more frequently. In the next revision I hope to have this issue addressed and hopefully fixed up, but the more information the better, of course.

**Comment by Murokyro** [comment]
No i did not touch the scripts and yes the client downloaded all the scripts in the resources folder. As far as i know i did not mess with the script loading at all, all i did was paste the app.asar then launched the client, all the scripts were downloaded correctly i think, whenever i compare them to the one i've downloaded on github they're the same files.

**Comment by Dubz9** [comment]
i had this problem as well but fixed it by restarting few times and thought nothing of it.
i did notice it is happening since latest pokeclicker update.
everything before that loaded correctly.

**Comment by Ephenia** [comment]
This issue should be fixed as of commit 444d7413069e86b87d1b231b09b956f0e0ed816f.
