### ISSUE TITLE
Autoclicker still gone

### ISSUE THREAD

**Issue by SlightlyWinged** [Ephenia/Pokeclicker-Scripts#212]
Using Firefox, my autoclicker disappeared a couple weeks ago. I had already completed everything so I wasn't too bothered until the update today. I've deleted and reinstalled it a few times over the past couple weeks, and even copy/pasted the code a couple times. Picture example below

![Picture](https://user-images.githubusercontent.com/112659964/188000083-e7530b17-0f04-41e5-aaa6-cb8a40e9603c.png)

**Comment by kevingrillet** [comment]
A way to fix this your side is to clear the localstorage for the website.

The problem is that the script was using ON/OFF but is now usind true/false for some parts.

On firefox, go on the website, then show dev tools (ctrl + shift + i), storage, local storage, right click, delete all.
On chrome, go on the website, then show dev tools (ctrl + shift + i), application, local storage, right click, clear.

**Comment by Ephenia** [comment]
[I made a guide along with a script](https://github.com/Ephenia/Pokeclicker-Scripts/issues/214) specifically for dealing with `localStorage` that's user friendly and for more tech illiterate people. I found even trying to give directions as simple to that to people wasn't as effective, unfortunately (I get that the developer tools can be intimidating especially to those who have never used it or are familiar). Also, still would need something anyway for the Desktop version of the game which using the script would still be the easier route for that currently if people need things fixed.
