### ISSUE TITLE
Auto Clicker rate change

### ISSUE THREAD

**Issue by Michael-DeLucia** [Ephenia/Pokeclicker-Scripts#300]
Auto clicker was running at 1000 clicks/second (at least that is what the UI was showing) then after a restart it has gone down to maximum of 100 clicks/second. When at 1000, the slider was fully to the left, and now with a maximum of 100 this is the right side of the slider.

This is on the desktop version of the client. I have tried to redownload the app.asar file but no change.

**Comment by Michael-DeLucia** [comment]
Thank you!

**Comment by Ephenia** [comment]
Javascript is also single threaded to add, which is why there's also such limitation to not just say the auto clicker, but as well as a game like Pokeclicker in general with how much can be going on whilst running optimally as possible. Some stuff may be unoptimized, but even with optimization, at some point there's just going to be bad performance just due to the nature of Javascript.
