### ISSUE TITLE
all script broken 

### ISSUE THREAD

**Issue by Elvundil** [Ephenia/Pokeclicker-Scripts#322]
hello since this morning on 09/07/2023 all the scripts no longer seem to work I tried to reinstall the extension allowing the use of script I also tried to use another extension, the version of pokeclicker and 0.10 .12 I use firefox 115.0.1 and I tested on google chrome 114 with last Tampermonkey version.

edit : the scripts still seem to work on the desktop application

**Comment by simcowking** [comment]
Downgraded to 3.1 and everything works. Something in 3.2 is keeping autoclick green and auto gym green (I had these green before upgrade though so may not be related, I just can't change them)

Also with file, even regular battling doesn't work. Only manual clicking.

**Comment by Elvundil** [comment]
disabled Additional Visual Settings and downgrade autoclicker to 3.1 and everything seems to work .

**Comment by macrc89** [comment]
3.2 broke the browser game

**Comment by NanouJen** [comment]
Good evening,
my name is NanouJen and I have the same problem since today, the automatic click does not work anymore on pokeclicker.
I tried to change the version with your fix but tamper monkey always gives me errors in the code and I don't have autoclick on the game now.

can someone help me? I don't know how to revert to previous versions of auto clicks.

Thank you in advance for your help.

**Comment by NanouJen** [comment]
Hello @umbralOptimatum, I am using tamper monkey script manager and "enhancedautocliker" script
I tried deleting the old script before copying your script and I also tried deleting the old script in order to create a new one to copy your script.

Once I copy the script to tamper monkey, it gives me errors in the script, and when I try to use pokecliker with it, the script does not appear.
My companion who is more geeky than me, has the same problem, also tried on his computer to copy and read the script, and it doesn't work either.

Maybe the error also comes from the tamper monkey script reader. I tried on 2 different browsers (chrome and opera) and also with another script and I have errors that are created each time when I click CTRL V.

what other script manager do you recommend?

I made some screenshots to show some of the errors that appear on tamper monkey when I copy the script. Of course, I use keyboard shortcuts to avoid any errors in copying the script.

![Capture d'écran 2023-07-10 180557](https://github.com/Ephenia/Pokeclicker-Scripts/assets/139078512/eaf4869c-27c5-46b3-a027-2334ec4475a5)
![Capture d'écran 2023-07-10 180731](https://github.com/Ephenia/Pokeclicker-Scripts/assets/139078512/f8ccacca-b443-4a54-9229-ca9414fc08bf)

**Comment by macrc89** [comment]
I use tempermonkey with chrome too and the new version with fix work well here

**Comment by NanouJen** [comment]
yes, script 3.2.1
google chrome Version 114.0.5735.199 (Build officiel) (64 bits)
tamper monkey 4.19.0

![Capture d'écran 2023-07-11 002046](https://github.com/Ephenia/Pokeclicker-Scripts/assets/139078512/8ac6d8d2-d695-40ca-a50f-a9fcf4f947c7)

**Comment by NanouJen** [comment]
![Capture d'écran 2023-07-11 005529](https://github.com/Ephenia/Pokeclicker-Scripts/assets/139078512/eae7d3ea-7fda-499c-8af5-210df5f5d434)

**Comment by NanouJen** [comment]
![Capture d'écran 2023-07-11 163431](https://github.com/Ephenia/Pokeclicker-Scripts/assets/139078512/2e247c6b-e73c-4445-85fe-085880fc1981)

**Comment by NanouJen** [comment]
Thanks for your help. It no longer works on google chrome but thanks to your link, I managed to install it on another browser (opera) and it works.

I went to this page to get the script : [(https://github.com/Ephenia/Pokeclicker-Scripts/pull/323/files)]
