### ISSUE TITLE
Automine Issue

### ISSUE THREAD

**Issue by thread123** [Ephenia/Pokeclicker-Scripts#346]
After the recent update the autominer is only using bombs, no matter what even if an item is found.

**Comment by JohnyDL** [comment]
I think this is intended behaviour, it should use bombs until every item is located and then mine out those items with the chisel, this actually saves you energy because there's a chance that a bomb would hit one of the item's covering layers and save you a chisel action... it's not perfectly optimal but it's subtly better than bomb until a new item is found, mine it out and repeat until all items are mined.

**Comment by thread123** [comment]
Oh i see, i didnt know it got changed, thanks.
