### ISSUE TITLE
[BUG REPORT] Autominer only buying one restore

### ISSUE THREAD

**Issue by TrainerRobo** [Ephenia/Pokeclicker-Scripts#53]
I have over 400 million pokecoins, and i set the purchasing threshold at 400 million, but it only buys one every time I open the game, and nothing more.

**Comment by TrainerRobo** [comment]
Thsi issue only seesm to happenw hen not on a route defeating pokemon. setting the purchase tthrewshold to 1 and sitting in a town will not ppurchase any, but as soon as i enter a route, it begins working as intended.

**Comment by Ephenia** [comment]
That's intended, you need to be actively defeating Pokémon in a route for the Auto Buying to occur—that's due to Small Restores only being bought when there is no price penalty. The price penalty is when you normally buy too many of one shop item and the price of said item increases. Defeating Pokémon is the only way to lower the price back to its original price.
