### ISSUE TITLE
Autohatchery sorting

### ISSUE THREAD

**Issue by kiaen1** [Ephenia/Pokeclicker-Scripts#6]
I dunno if I am just dumb, but I had no clue that you changed Autohatchery sorting to be the party list until I went through the code, so I could figure out how to set it to go by breeding eff.

Don't be like me if anyone else sees this. 

Maybe add it to the autohachery info?

**Comment by bssipes** [comment]
@kiaen1 Could you provide details on what you modified to be able to sort by Breeding Efficiency in the meantime?

**Comment by Ephenia** [comment]
This was an intentional thing that I had done back when a game update came that had broke the original scripts functionality as the Hatchery had been slightly redesigned to function differently. It was more of lazy fix on my behalf and offering a temporary solution so that the Auto Hatchery could still work, but the next update it will be able to work more of how it originally did. You'll be able to sort through the Daycare again as well as still sort via your Pokémon List (basically they'll sort each other and sync like before).

**Comment by Ephenia** [comment]
This should now be fixed and addressed as of commit bfe4fde53c820433584265855fec39c54e289ba7.
